export { default as Home } from './Home'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Contact  } from './Contact'
export { default as AddProject } from './AddProject'
export { default as Gallery } from './Blogposts'
export { default as Shop } from './Shop'
